/** جامع الحي - Frontend
 * مبدأ مهم: الواجهة للتجربة السهلة فقط، والحماية الحقيقية داخل Worker.
 */
const API_BASE="https://mosque-api.5jfwpmvt9w.workers.dev";
const state={me:null,csrf:sessionStorage.getItem("mosque_csrf")||"",prayers:[],selectedPrayer:null,selectedEvent:null,prayerPayload:null,countdownTimer:null,countdownAnchorMs:0,lastDelegationLink:"",delegationAck:false,delegationDays:[],transitionShownKey:"",autoRefreshKeys:new Set()};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function registerPWA(){if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}))}}
registerPWA();

function status(el,msg,type="info"){if(!el)return;el.textContent=msg;el.className=`status-box ${type}`}
function hide(el){el?.classList.add("hidden")}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function api(path,opt={}){const method=(opt.method||"GET").toUpperCase(),headers=new Headers(opt.headers||{});if(opt.body&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");if(!["GET","HEAD","OPTIONS"].includes(method)&&state.csrf)headers.set("X-CSRF-Token",state.csrf);return fetch(`${API_BASE}${path}`,{...opt,method,headers,credentials:"include",cache:"no-store"})}
async function apiJSON(path,opt={}){const r=await api(path,opt),data=await r.json().catch(()=>({}));return{r,data}}

// لا نطرد المستخدم من الداشبورد بسبب انقطاع لحظي؛ نجرب 3 مرات أولًا.
async function session(){for(let i=0;i<3;i++){try{const {r,data}=await apiJSON("/api/auth/me");if(r.status===401)return{kind:"unauthorized"};if(r.ok&&data.authenticated){state.me=data.user;if(data.csrf_token){state.csrf=data.csrf_token;sessionStorage.setItem("mosque_csrf",state.csrf)}return{kind:"ok",user:data.user}}}catch{}if(i<2)await sleep(350*(i+1))}return{kind:"network"}}
async function protect(role){const s=await session();if(s.kind==="unauthorized"){location.replace("./index.html");return null}if(s.kind==="network"){status($("#globalStatus"),"تعذر التحقق من الجلسة بسبب الاتصال. الصفحة لن تختفي؛ حدّثها بعد عودة الشبكة.","error");return null}if(role&&s.user.role!==role&&!(role==="MUADHIN"&&s.user.role==="TEST_MUADHIN")){location.replace(s.user.role==="ADMIN"?"./admin.html":"./dashboard.html");return null}return s.user}
function err(code){return({INVALID_CREDENTIALS:"اسم المستخدم أو كلمة المرور غير صحيحة.",TOO_MANY_ATTEMPTS:"محاولات كثيرة. انتظر قليلًا ثم حاول.",CSRF_FAILED:"انتهت حماية الجلسة. سجل الدخول من جديد.",OUTSIDE_CONFIRM_WINDOW:"لا يمكن تأكيد الأذان قبل دخول وقته.",MOSQUE_LOCATION_REQUIRED:"أدخل موقع الجامع من لوحة المدير أولًا.",WEAK_PASSWORD:"كلمة المرور: 10 خانات على الأقل وتحتوي حروفًا وأرقامًا.",DUPLICATE_USER_OR_TELEGRAM:"اسم المستخدم أو حساب تيليجرام مستخدم بالفعل.",INVALID_DATE_RANGE:"اختر مدة صحيحة تبدأ من اليوم أو بعده.",INVALID_DELEGATION:"تحقق من الرمز السري للتفويض والصلوات المسموحة.",INVALID_DELEGATION_AUTH:"رابط التفويض أو الرمز السري غير صحيح.",NO_CURRENT_PRAYER:"لم يدخل وقت أي صلاة بعد.",PRAYER_NOT_ALLOWED:"هذه الصلاة غير مشمولة في التفويض.",PRAYER_NOT_STARTED:"لم يدخل وقت الصلاة بعد.",DELEGATION_EXPIRED:"انتهت صلاحية التفويض.",PAST_PRAYER_DELEGATION:"لا يمكن تفويض صلاة انتهى وقتها في يوم البداية.",ADHAN_NOT_CONFIRMED_WARNING:"لم يتم إرسال إشعار أذان هذه الصلاة.",CANNOT_DELETE_SELF:"لا يمكن حذف الحساب الذي تستخدمه الآن.",USER_NOT_FOUND:"الحساب غير موجود أو تم حذفه.",DELETE_USER_FAILED:"تعذر حذف الحساب.",TEST_ACCOUNT_REQUIRED:"هذه الميزة متاحة لمؤذن التجربة فقط.",INVALID_TEST_TIME:"تحقق من التاريخ والوقت التجريبي.",INVALID_MESSAGE_TEMPLATE:"تحقق من نص الرسالة.",INVALID_BROADCAST:"اكتب رسالة صحيحة واختر المستلمين.",ADHAN_CLOSED_AFTER_IQAMA:"تمت الإقامة ولا يمكن تأكيد الأذان بعدها.",INVALID_ADHAN_WINDOW:"مهلة تأكيد الأذان يجب أن تكون بين 1 و120 دقيقة."})[code]||"تعذر تنفيذ العملية."}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function openModal(el){el.classList.remove("hidden");el.setAttribute("aria-hidden","false");document.body.classList.add("modal-open")}
function closeModal(el){el.classList.add("hidden");el.setAttribute("aria-hidden","true");if(!document.querySelector(".modal-layer:not(.hidden)"))document.body.classList.remove("modal-open")}

async function initLogin(){const form=$("#loginForm");if(!form)return;const old=await session();if(old.kind==="ok"){location.replace(old.user.role==="ADMIN"?"./admin.html":"./dashboard.html");return}$("#togglePassword")?.addEventListener("click",()=>{const p=$("#password");p.type=p.type==="password"?"text":"password"});form.addEventListener("submit",async e=>{e.preventDefault();const b=$("#loginBtn"),box=$("#loginStatus");hide(box);b.disabled=true;b.textContent="جاري الدخول…";try{const {r,data}=await apiJSON("/api/auth/login",{method:"POST",body:JSON.stringify({username:$("#username").value.trim(),password:$("#password").value})});if(!r.ok){status(box,err(data.error),"error");return}state.csrf=data.csrf_token||"";sessionStorage.setItem("mosque_csrf",state.csrf);location.replace(data.user.role==="ADMIN"?"./admin.html":"./dashboard.html")}catch{status(box,"تعذر الاتصال بالخادم.","error")}finally{b.disabled=false;b.textContent="دخول"}})}
async function logout(){try{await apiJSON("/api/auth/logout",{method:"POST",body:"{}"})}catch{}sessionStorage.removeItem("mosque_csrf");location.replace("./index.html")}

function time12(v){if(!v||!/^[0-2]?\d:[0-5]\d$/.test(v))return v||"—:—";let[h,m]=v.split(":").map(Number),suffix=h<12?"ص":"م";h=h%12||12;return `${h}:${String(m).padStart(2,"0")} ${suffix}`}
function countdownText(ms){if(ms<=0)return "الآن";const total=Math.floor(ms/1000),h=Math.floor(total/3600),m=Math.floor((total%3600)/60),sec=total%60;if(h>0)return `${h} س ${m} د ${String(sec).padStart(2,"0")} ث`;return `${m} د ${String(sec).padStart(2,"0")} ث`}
function startCountdowns(){if(state.countdownTimer)clearInterval(state.countdownTimer);state.countdownAnchorMs=Date.now();const tick=()=>{const d=state.prayerPayload;if(!d)return;const focus=d.focus_prayer||d.next_prayer||null,elapsed=Date.now()-state.countdownAnchorMs,adhanEl=$("#nextPrayerAdhanCountdown"),iqamaEl=$("#nextPrayerIqamaCountdown"),a=Number(focus?.adhan_in_seconds),i=Number(focus?.iqama_in_seconds);if(adhanEl)adhanEl.textContent=Number.isFinite(a)?countdownText(a*1000-elapsed):"—";if(iqamaEl)iqamaEl.textContent=Number.isFinite(i)?countdownText(i*1000-elapsed):"—";const elapsedSec=Math.floor(elapsed/1000),base=`${focus?.date||d.date}:${focus?.name||"NONE"}`;for(const [kind,due] of [["ADHAN",a],["IQAMA",i],["EXPIRE",Number.isFinite(i)?i+600:NaN]]){const key=`${base}:${kind}`;if(Number.isFinite(due)&&due>0&&elapsedSec>=due&&!state.autoRefreshKeys.has(key)){state.autoRefreshKeys.add(key);setTimeout(()=>loadPrayers().catch(()=>{}),50)}}};tick();state.countdownTimer=setInterval(tick,1000)}
async function loadPrayers(){const {r,data}=await apiJSON("/api/prayers/today");if(!r.ok){status($("#globalStatus"),err(data.error),"warning");return}state.prayerPayload=data;state.prayers=data.prayers||[];state.selectedPrayer=data.action_prayer||data.current_prayer||null;if(!state.prayers.length)return;const current=state.prayers.find(p=>p.name===(data.action_prayer||data.current_prayer))||null,focus=data.focus_prayer||data.next_prayer||state.prayers[0];if($("#currentPrayer"))$("#currentPrayer").textContent=focus?.name_ar||"—";if($("#adhanTime"))$("#adhanTime").textContent=time12(focus?.adhan);if($("#iqamaTime"))$("#iqamaTime").textContent=time12(focus?.iqama);if($("#adhanTimeLabel"))$("#adhanTimeLabel").textContent=focus?`أذان ${focus.name_ar}`:"وقت الأذان";if($("#iqamaTimeLabel"))$("#iqamaTimeLabel").textContent=focus?`إقامة ${focus.name_ar}`:"وقت الإقامة";if($("#todayDate"))$("#todayDate").textContent=hijriText(data.date);const box=$("#prayerTimes");if(box)box.innerHTML=state.prayers.map(p=>`<div class="prayer-choice ${p.name===focus?.name&&(!focus?.date||focus.date===data.date)?"active":""}" ${p.name===focus?.name&&(!focus?.date||focus.date===data.date)?'aria-current="true"':''}><strong>${esc(p.name_ar)}</strong><span>${esc(time12(p.adhan))}</span><small>${esc(time12(p.iqama))}</small></div>`).join("");const adhan=$("#adhanStatus"),iqama=$("#iqamaStatus");if(adhan)adhan.textContent=current?.adhan_confirmed?"تم إرسال الإشعار":"لم يتم التأكيد";if(iqama)iqama.textContent=current?.iqama_confirmed?"تم إرسال الإشعار":"لم يتم التأكيد";const ab=$("#adhanBadge"),ib=$("#iqamaBadge");if(ab){ab.textContent=current?.adhan_confirmed?"تم الإرسال":"بانتظار المؤذن";ab.className=`state ${current?.adhan_confirmed?"state-success":"state-waiting"}`}if(ib){ib.textContent=current?.iqama_confirmed?"تم الإرسال":"بانتظار المؤذن";ib.className=`state ${current?.iqama_confirmed?"state-success":"state-waiting"}`}updateMuadhinActionButtons(data,current);showMissedPrayerPrompt(data);startCountdowns()}
function updateMuadhinActionButtons(data,current){$$('.sensitive-action').forEach(b=>{const type=String(b.dataset.action||'').toUpperCase(),done=type==='ADHAN'?!!current?.adhan_confirmed:!!current?.iqama_confirmed,available=type==='ADHAN'?!!data.action_adhan_available:!!data.action_iqama_available;if(done){b.disabled=true;b.innerHTML=type==='ADHAN'?'<span>✓</span> تم إرسال إشعار الأذان':'<span>✓</span> تم إرسال إشعار الإقامة';return}if(!available){b.disabled=true;b.innerHTML=type==='ADHAN'?(data.action_iqama_available?'<span>🔒</span> انتهى وقت تأكيد الأذان':'<span>⏳</span> لم يحن وقت الأذان بعد'):'<span>⏳</span> لم يحن وقت الإقامة بعد';return}b.disabled=false;b.innerHTML=type==='ADHAN'?'<span>🔔</span> تأكيد رفع الأذان':'<span>🕌</span> تأكيد إقامة الصلاة'})}
function showMissedPrayerPrompt(){/* v18: prayer state advances by time only; no manual transition UI. */}
async function loadAdhan(){const {r,data}=await apiJSON("/api/muadhin/adhan-settings");if(!r.ok)return;for(const x of data.settings||[]){const i=$(`#adhan_${x.prayer_name}`);if(i)i.value=x.offset_minutes}}
async function saveAdhan(e){e.preventDefault();const s={};for(const i of $$("[data-adhan-prayer]")){const v=Number(i.value);if(!Number.isInteger(v)||v<0||v>180){status($("#adhanStatusBox"),"القيم من 0 إلى 180 دقيقة.","warning");return}s[i.dataset.adhanPrayer]=v}const b=$("#saveAdhanBtn");b.disabled=true;try{const {r,data}=await apiJSON("/api/muadhin/adhan-settings",{method:"POST",body:JSON.stringify({settings:s})});status($("#adhanStatusBox"),r.ok?"تم حفظ إضافات وقت الأذان.":err(data.error),r.ok?"success":"error")}finally{b.disabled=false}}
async function loadIqama(){const {r,data}=await apiJSON("/api/muadhin/iqama-settings");if(!r.ok)return;for(const x of data.settings||[]){const i=$(`#iqama_${x.prayer_name}`);if(i)i.value=x.offset_minutes}}
async function saveIqama(e){e.preventDefault();const s={};for(const i of $$('[data-prayer]')){const v=Number(i.value);if(!Number.isInteger(v)||v<0||v>120){status($("#iqamaStatusBox"),"القيم من 0 إلى 120 دقيقة.","warning");return}s[i.dataset.prayer]=v}const b=$("#saveIqamaBtn");b.disabled=true;try{const {r,data}=await apiJSON("/api/muadhin/iqama-settings",{method:"POST",body:JSON.stringify({settings:s})});status($("#iqamaStatusBox"),r.ok?"تم حفظ فواصل الإقامة.":err(data.error),r.ok?"success":"error");if(r.ok)await loadPrayers()}finally{b.disabled=false}}
async function openConfirm(type){
  state.selectedEvent=type;
  // Refresh immediately before opening so the prayer name can never be stale.
  const {r,data}=await apiJSON("/api/prayers/today");
  if(!r.ok){status($("#globalStatus"),err(data.error),"warning");return}
  state.prayerPayload=data;state.prayers=data.prayers||[];state.selectedPrayer=data.action_prayer||data.current_prayer||null;
  const p=state.prayers.find(x=>x.name===state.selectedPrayer)||((data.next_prayer&&data.next_prayer.name===state.selectedPrayer)?data.next_prayer:null);
  if(!p){status($("#globalStatus"),"لا توجد صلاة متاحة للتأكيد الآن.","warning");return}
  $("#modalTitle").textContent=type==="ADHAN"?"تأكيد رفع الأذان":"تأكيد إقامة الصلاة";
  $("#modalPrayerName").textContent=p.name_ar;
  const warn=$("#iqamaWarning"),confirmBtn=$("#modalConfirmBtn"),missedAdhan=type==="IQAMA"&&!p.adhan_confirmed;
  warn?.classList.toggle("hidden",!missedAdhan);
  if(confirmBtn){confirmBtn.textContent="نعم، أنا متأكد من إرسال الإشعار";confirmBtn.disabled=!!data.action_waiting}
  const wait=$("#modalWaitingMessage");if(wait){wait.classList.toggle("hidden",!data.action_waiting);wait.textContent=data.action_waiting?`لم يدخل وقت ${p.name_ar} بعد، وسيصبح التأكيد متاحًا عند دخول وقت الأذان.`:""}
  hide($("#modalStatus"));openModal($("#confirmModal"))
}
function deliveryMessage(data){if(data.already_confirmed)return["تم التأكيد مسبقًا.","info"];const d=data.delivery||{};if(Number(d.total)===0)return["تم تسجيل التأكيد، ولا يوجد مشتركون نشطون لإرسال إشعار لهم.","info"];if(Number(d.pending)===0&&Number(d.failed)===0&&Number(d.success)===Number(d.total))return["تم إرسال الإشعار بنجاح ✅\nكتب الله أجرك","success"];if(Number(d.pending)>0)return[`تم التأكيد. وصل الإشعار إلى ${d.success||0} من ${d.total||0}، والباقي قيد إعادة المحاولة.`,"warning"];return[`تم التأكيد، لكن الإرسال لم ينجح بالكامل (${d.success||0}/${d.total||0}).`,"warning"]}
function askFinalConfirmation(){
  const p=state.prayers.find(x=>x.name===state.selectedPrayer)||state.prayerPayload?.next_prayer;
  $("#finalModalPrayerName").textContent=p?.name_ar||"—";
  $("#finalModalText").textContent=state.selectedEvent==="ADHAN"?"سيتم الآن إرسال إشعار الأذان للمشتركين. هل تريد المتابعة؟":"سيتم الآن إرسال إشعار الإقامة للمشتركين. هل تريد المتابعة؟";
  openModal($("#finalConfirmModal"));
}
async function confirmAction(){
  const box=$("#finalModalStatus"),b=$("#finalConfirmBtn"),p=state.prayers.find(x=>x.name===state.selectedPrayer),ackMissing=state.selectedEvent==="IQAMA"&&!p?.adhan_confirmed;
  b.disabled=true;try{
    const {r,data}=await apiJSON("/api/muadhin/confirm",{method:"POST",body:JSON.stringify({event_type:state.selectedEvent,ack_missing_adhan:ackMissing})});
    if(!r.ok){if(data.error==="ADHAN_NOT_CONFIRMED_WARNING"){$("#iqamaWarning")?.classList.remove("hidden");closeModal($("#finalConfirmModal"));status($("#modalStatus"),"راجع التنبيه ثم اضغط التأكيد مرة أخرى.","warning")}else status(box,err(data.error),"error");return}
    const [msg,type]=deliveryMessage(data);status(box,msg,type);await loadPrayers();if(type==="success")setTimeout(()=>{closeModal($("#finalConfirmModal"));closeModal($("#confirmModal"))},1800)
  }catch{status(box,"تعذر الاتصال بالخادم.","error")}finally{b.disabled=false}
}
const PRAYER_AR={FAJR:"الفجر",DHUHR:"الظهر",ASR:"العصر",MAGHRIB:"المغرب",ISHA:"العشاء"};
function parsePrayerNames(raw){try{const a=Array.isArray(raw)?raw:JSON.parse(raw||"[]");return a.map(x=>PRAYER_AR[x]||x).join("، ")}catch{return String(raw||"")}}
function todayIso(tz="Asia/Riyadh"){const p=new Intl.DateTimeFormat("en-CA",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),o={};for(const x of p)o[x.type]=x.value;return `${o.year}-${o.month}-${o.day}`}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{const t=document.createElement("textarea");t.value=text;t.style.position="fixed";t.style.opacity="0";document.body.appendChild(t);t.select();const ok=document.execCommand("copy");t.remove();return ok}}
function toast(msg,type="success"){let t=$("#appToast");if(!t){t=document.createElement("div");t.id="appToast";t.className="app-toast";t.setAttribute("role","status");document.body.appendChild(t)}t.textContent=msg;t.className=`app-toast show ${type}`;clearTimeout(toast._tm);toast._tm=setTimeout(()=>t.classList.remove("show"),2600)}
function ummData(){return window.UMMALQURA_DATA||null}
function hijriPairByG(g){return ummData()?.pairs?.find(x=>x[0]===g)||null}
function hijriPairByH(h){return ummData()?.pairs?.find(x=>x[1]===h)||null}
function hijriText(g){const p=hijriPairByG(g);if(!p)return g;const[y,m,d]=p[1].split("-").map(Number),months=["محرم","صفر","ربيع الأول","ربيع الآخر","جمادى الأولى","جمادى الآخرة","رجب","شعبان","رمضان","شوال","ذو القعدة","ذو الحجة"];return `${d} ${months[m-1]} ${y}هـ`}
function setSelectOptions(el,items,value){if(!el)return;el.innerHTML=items.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join("");if(value!=null&&items.some(x=>String(x.value)===String(value)))el.value=String(value)}
function weekdayAr(g){try{return new Intl.DateTimeFormat("ar-SA",{weekday:"long",timeZone:state.prayerPayload?.mosque?.timezone||"Asia/Riyadh"}).format(new Date(`${g}T12:00:00Z`))}catch{return ""}}
function hijriMinGregorian(){return state.prayerPayload?.date||todayIso(state.prayerPayload?.mosque?.timezone)}
function hijriChoices(prefix,greg){const minG=hijriMinGregorian(),target=greg&&greg>=minG?greg:minG,pair=hijriPairByG(target)||ummData()?.pairs?.find(x=>x[0]>=minG);if(!pair)return;const[y,m,d]=pair[1].split("-").map(Number),minPair=hijriPairByG(minG),minY=Number(minPair?.[1]?.slice(0,4)||y),maxY=Number(ummData()?.hijriTo||y);setSelectOptions($(`#${prefix}Year`),Array.from({length:maxY-minY+1},(_,i)=>({value:minY+i,label:String(minY+i)})),y);updateHijriMonths(prefix,m,d)}
function updateHijriMonths(prefix,wantedMonth,wantedDay){const y=Number($(`#${prefix}Year`)?.value),minG=hijriMinGregorian(),rows=(ummData()?.pairs||[]).filter(x=>x[0]>=minG&&Number(x[1].slice(0,4))===y),months=[...new Set(rows.map(x=>Number(x[1].slice(5,7))))].sort((a,b)=>a-b),names=["محرم","صفر","ربيع الأول","ربيع الآخر","جمادى الأولى","جمادى الآخرة","رجب","شعبان","رمضان","شوال","ذو القعدة","ذو الحجة"],chosen=months.includes(Number(wantedMonth))?Number(wantedMonth):months[0];setSelectOptions($(`#${prefix}Month`),months.map(m=>({value:m,label:names[m-1]})),chosen);updateHijriDays(prefix,wantedDay)}
function updateHijriDays(prefix,wantedDay){const y=Number($(`#${prefix}Year`)?.value),m=Number($(`#${prefix}Month`)?.value),minG=hijriMinGregorian(),rows=(ummData()?.pairs||[]).filter(x=>x[0]>=minG&&Number(x[1].slice(0,4))===y&&Number(x[1].slice(5,7))===m),days=[...new Set(rows.map(x=>Number(x[1].slice(8,10))))].sort((a,b)=>a-b),chosen=days.includes(Number(wantedDay))?Number(wantedDay):days[0];setSelectOptions($(`#${prefix}Day`),days.map(day=>{const row=rows.find(x=>Number(x[1].slice(8,10))===day);return{value:day,label:`${day} — ${weekdayAr(row?.[0]||"")}`}}),chosen);syncHijriDate(prefix)}
function syncHijriDate(prefix){const y=$(`#${prefix}Year`)?.value,m=$(`#${prefix}Month`)?.value,d=$(`#${prefix}Day`)?.value;if(!y||!m||!d)return;const h=`${y}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`,pair=hijriPairByH(h),hidden=$(`#delegation${prefix}`);if(hidden&&pair)hidden.value=pair[0];const minG=hijriMinGregorian();if(hidden&&hidden.value<minG){hidden.value=minG;hijriChoices(prefix,minG);return}const wd=$(`#${prefix}Weekday`);if(wd)wd.textContent=pair?weekdayAr(pair[0]):"—";refreshDelegationPrayerChoices()}
function schedulePrayerNames(ps){return (ps||[]).map(x=>PRAYER_AR[x]||x).join("، ")}
function renderDelegationSchedule(){const list=$("#delegationScheduleList");if(!list)return;const days=[...state.delegationDays].sort((a,b)=>a.date.localeCompare(b.date));if(!days.length){list.innerHTML='<p class="muted">لم تضف أي يوم بعد.</p>';return}list.innerHTML=days.map(d=>`<article class="delegation-schedule-item" data-schedule-date="${esc(d.date)}"><div><strong>${esc(weekdayAr(d.date))} · ${esc(hijriText(d.date))}</strong><small>${esc(schedulePrayerNames(d.prayers))}</small></div><button type="button" class="btn btn-ghost btn-sm remove-schedule-day" data-date="${esc(d.date)}">حذف اليوم</button></article>`).join("");$$('.remove-schedule-day',list).forEach(b=>b.addEventListener('click',()=>{state.delegationDays=state.delegationDays.filter(x=>x.date!==b.dataset.date);renderDelegationSchedule()}))}
function addDelegationDay(){const date=$("#delegationFrom")?.value,ps=$$('#delegationPrayers input[type="checkbox"]:checked:not(:disabled)').map(x=>x.value);if(!date){status($("#delegationStatus"),"اختر تاريخ اليوم أولًا.","warning");return}if(!ps.length){status($("#delegationStatus"),"اختر صلاة واحدة على الأقل لهذا اليوم.","warning");return}const row={date,prayers:[...new Set(ps)]};const i=state.delegationDays.findIndex(x=>x.date===date);if(i>=0)state.delegationDays[i]=row;else state.delegationDays.push(row);state.delegationDays.sort((a,b)=>a.date.localeCompare(b.date));$$("#delegationPrayers input[type=checkbox]").forEach(x=>x.checked=false);hide($("#delegationStatus"));renderDelegationSchedule();toast(`تمت إضافة ${weekdayAr(date)} للتفويض ✅`)}
async function loadDelegations(){const {r,data}=await apiJSON("/api/muadhin/delegations");if(!r.ok)return;const list=$("#delegationsList");if(!list)return;const items=data.delegations||[],today=state.prayerPayload?.date||todayIso(state.prayerPayload?.mosque?.timezone);list.innerHTML=items.map(d=>{const upcoming=d.valid_from>today,label=upcoming?"تفويض قادم":"تفويض حالي",schedule=Array.isArray(d.schedule)&&d.schedule.length?d.schedule:null,detail=schedule?schedule.map(x=>`${weekdayAr(x.date)} ${hijriText(x.date)}: ${schedulePrayerNames(x.prayers)}`).join(" | "):parsePrayerNames(d.allowed_prayers);return `<article class="simple-row current-delegation" data-delegation-id="${d.id}"><div><span class="state ${upcoming?"":"state-success"}">${label}</span><strong>${esc(detail)}</strong><small>${esc(hijriText(d.valid_from))}${d.valid_until!==d.valid_from?` — ${esc(hijriText(d.valid_until))}`:""}</small></div><div class="delegation-row-actions"><button class="btn btn-secondary btn-sm copy-current-delegation" data-id="${d.id}">نسخ رابط التفويض</button><button class="btn btn-ghost btn-sm revoke" data-id="${d.id}">إلغاء التفويض</button></div></article>`}).join("")||"<p class='muted empty-delegations'>لا يوجد تفويض حالي.</p>";$$('.copy-current-delegation',list).forEach(b=>b.addEventListener('click',()=>copyDelegationLink(Number(b.dataset.id),b)));$$('.revoke',list).forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;const {r,data}=await apiJSON(`/api/muadhin/delegations/${b.dataset.id}`,{method:'PATCH',body:'{}'});if(r.ok){b.closest('[data-delegation-id]')?.remove();if(!list.querySelector('[data-delegation-id]'))list.innerHTML="<p class='muted empty-delegations'>لا يوجد تفويض حالي.</p>";toast("تم إزالة التفويض بنجاح ✅")}else{b.disabled=false;toast(err(data.error),"error")}}))}
function refreshDelegationPrayerChoices(){const from=$("#delegationFrom")?.value,today=state.prayerPayload?.date||todayIso(state.prayerPayload?.mosque?.timezone),startsToday=from===today;for(const label of $$("#delegationPrayers label")){const input=$("input",label),p=state.prayers.find(x=>x.name===input?.value);const expired=startsToday&&Boolean(p?.delegation_expired);label.classList.toggle("prayer-expired",!!expired);input.disabled=!!expired;if(expired)input.checked=false}const note=$("#delegationPrayerHint");if(note)note.textContent=startsToday?"اختر صلوات هذا اليوم. الصلوات التي انتهى وقتها اليوم غير متاحة.":"اختر الصلوات المطلوبة لهذا اليوم، ثم اضغط إضافة هذا اليوم."}
async function setupDelegationDates(){try{const {r,data}=await apiJSON("/api/prayers/today");if(r.ok){state.prayerPayload=data;state.prayers=data.prayers||[]}}catch{}const tz=state.prayerPayload?.mosque?.timezone||"Asia/Riyadh",today=state.prayerPayload?.date||todayIso(tz);state.delegationDays=[];$("#delegationFrom").value=today;hijriChoices("From",today);for(const prefix of ["From"]){$(`#${prefix}Year`)?.addEventListener("change",()=>updateHijriMonths(prefix));$(`#${prefix}Month`)?.addEventListener("change",()=>updateHijriDays(prefix));$(`#${prefix}Day`)?.addEventListener("change",()=>syncHijriDate(prefix))}refreshDelegationPrayerChoices();renderDelegationSchedule()}
async function createDelegation(e){e.preventDefault();if(!state.delegationDays.length){status($("#delegationStatus"),"أضف يومًا واحدًا على الأقل للتفويض.","warning");return}const payload={schedule:state.delegationDays.map(x=>({date:x.date,prayers:[...x.prayers]})),pin:$("#delegationPin").value};const submit=$("#createDelegationBtn");if(submit)submit.disabled=true;try{const {r,data}=await apiJSON('/api/muadhin/delegations',{method:'POST',body:JSON.stringify(payload)});if(!r.ok){status($("#delegationStatus"),err(data.error),'error');return}state.lastDelegationId=Number(data.delegation_id)||null;hide($("#delegationStatus"));const box=$("#delegationCreated");box?.classList.remove("hidden");const copyBtn=$("#copyDelegationBtn");if(copyBtn)copyBtn.dataset.id=String(state.lastDelegationId||"");state.delegationDays=[];renderDelegationSchedule();$("#delegationPin").value="";await loadDelegations()}finally{if(submit)submit.disabled=false}}
let delegationCopyModalTimer=null;
function closeDelegationCopyModal(){clearTimeout(delegationCopyModalTimer);delegationCopyModalTimer=null;closeModal($("#delegationCopyModal"))}
function showDelegationCopyModal(){const modal=$("#delegationCopyModal");if(!modal)return;openModal(modal);clearTimeout(delegationCopyModalTimer);delegationCopyModalTimer=setTimeout(closeDelegationCopyModal,7000)}
async function copyDelegationLink(id,button=null){
 const delegationId=Number(id||state.lastDelegationId||$("#copyDelegationBtn")?.dataset.id);if(!delegationId)return;
 const btn=button||$("#copyDelegationBtn");if(btn)btn.disabled=true;
 try{
   const {r,data}=await apiJSON(`/api/muadhin/delegations/${delegationId}/link`,{method:"POST",body:"{}"});
   if(!r.ok){toast(err(data.error),"error");return}
   const base=location.href.replace(/[^/]+(?:\?.*)?$/,'');
   const link=`${base}delegate.html?token=${encodeURIComponent(data.token)}`;
   const ok=await copyText(link);
   if(ok)showDelegationCopyModal();else toast("تعذر النسخ تلقائيًا. جرّب من متصفح حديث.","error");
 }finally{if(btn)btn.disabled=false}
}


async function loadTestClock(){const {r,data}=await apiJSON("/api/muadhin/test-clock");if(!r.ok){status($("#testClockStatus"),err(data.error),"error");return}const date=$("#testClockDate"),time=$("#testClockTime");if(date)date.value=data.virtual_date||"";if(time)time.value=data.virtual_time||"";status($("#testClockStatus"),`${data.enabled?"الوقت التجريبي الحالي":"الوقت الحقيقي الحالي"}: ${data.virtual_date||"—"} · ${data.virtual_time||"—"} (${data.timezone||"Asia/Riyadh"})`,"info")}
async function setTestClock(){const date=$("#testClockDate")?.value,time=$("#testClockTime")?.value,btn=$("#setTestClockBtn");if(!date||!time){status($("#testClockStatus"),"اختر التاريخ والوقت.","warning");return}btn.disabled=true;try{const {r,data}=await apiJSON("/api/muadhin/test-clock",{method:"POST",body:JSON.stringify({date,time})});if(!r.ok){status($("#testClockStatus"),err(data.error),"error");return}status($("#testClockStatus"),`تم ضبط الساعة على ${data.date||date} ${data.time||time}. الساعة الآن تتحرك طبيعيًا.`,"success");await loadPrayers()}finally{btn.disabled=false}}
async function resetTestSession(){const btn=$("#resetTestSessionBtn");btn.disabled=true;try{const {r,data}=await apiJSON("/api/muadhin/test-clock/reset",{method:"POST",body:"{}"});if(!r.ok){status($("#testClockStatus"),err(data.error),"error");return}status($("#testClockStatus"),"بدأت تجربة جديدة مستقلة. لن تختلط تأكيداتها بالتجربة السابقة أو بالصلاة الحقيقية.","success");await loadPrayers()}finally{btn.disabled=false}}
async function initTestClock(){const card=$("#testClockCard");card?.classList.remove("hidden");await loadTestClock();$("#setTestClockBtn")?.addEventListener("click",setTestClock);$("#resetTestSessionBtn")?.addEventListener("click",resetTestSession)}

async function initMuadhin(){if(!$("#currentPrayer"))return;const me=await protect();if(!me)return;if(me.role==='ADMIN'){location.replace('./admin.html');return}$("#userWelcome").textContent=`${me.name} · ${me.role==="TEST_MUADHIN"?"مؤذن تجربة":"مؤذن"}`;if(me.role==="TEST_MUADHIN")await initTestClock();await loadPrayers();$$('.sensitive-action').forEach(b=>b.addEventListener('click',()=>openConfirm(b.dataset.action.toUpperCase())));$$('[data-modal-close]').forEach(b=>b.addEventListener('click',()=>closeModal($("#confirmModal"))));$$('[data-final-modal-close]').forEach(b=>b.addEventListener('click',()=>closeModal($("#finalConfirmModal"))));$("#modalConfirmBtn")?.addEventListener('click',askFinalConfirmation);$("#finalConfirmBtn")?.addEventListener('click',confirmAction);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal($("#finalConfirmModal"));closeModal($("#confirmModal"))}})}
async function initAdhanSettingsPage(){if(!$("#adhanForm"))return;const me=await protect("MUADHIN");if(!me)return;await loadAdhan();$("#adhanForm")?.addEventListener("submit",saveAdhan);$$("[data-adhan-step]").forEach(b=>b.addEventListener("click",()=>{const i=$(`#adhan_${b.dataset.target}`);if(!i)return;i.value=Math.max(0,Math.min(180,Number(i.value||0)+Number(b.dataset.adhanStep||0)))}))}
async function initIqamaSettingsPage(){if(!$(".iqama-settings-page"))return;const me=await protect("MUADHIN");if(!me)return;await loadIqama();$("#iqamaForm")?.addEventListener('submit',saveIqama);$$('[data-step]').forEach(b=>b.addEventListener('click',()=>{const i=$(`#iqama_${b.dataset.target}`);i.value=Math.max(0,Math.min(120,(Number(i.value)||0)+Number(b.dataset.step)))}))}

async function adminStats(){const {r,data}=await apiJSON('/api/admin/overview');if(!r.ok)return;if($("#adminSubscribersTotal"))$("#adminSubscribersTotal").textContent=data.stats.total_subscribers??0;if($("#adminSubscribers"))$("#adminSubscribers").textContent=data.stats.active_subscribers??0;if($("#adminSubscribersCancelled"))$("#adminSubscribersCancelled").textContent=data.stats.cancelled_subscribers??0;if($("#adminUsers"))$("#adminUsers").textContent=data.stats.active_muadhins??0}
async function loadUsers(){const {r,data}=await apiJSON('/api/admin/users');if(!r.ok)return;$("#usersList").innerHTML=(data.users||[]).map(u=>`<article class="simple-row account-row"><div class="account-main"><strong>${esc(u.first_name||u.login_username)} <span class="state ${u.role==='ADMIN'?'state-admin':'state-muadhin'}">${u.role==='ADMIN'?'مدير':u.role==='TEST_MUADHIN'?'مؤذن تجربة':'مؤذن'}</span></strong><small>@${esc(u.login_username)} ${u.telegram_chat_id?'· تيليجرام مربوط':''}</small></div><div class="account-actions">${u.role!=='ADMIN'?`<button class="btn btn-ghost btn-sm toggle-user" data-id="${u.id}" data-active="${Number(u.is_active)===1?0:1}">${Number(u.is_active)===1?'تعطيل':'تفعيل'}</button>`:''}${state.me&&Number(u.id)!==Number(state.me.id)?`<button class="btn btn-delete-account btn-sm delete-user" data-id="${u.id}" data-name="${esc(u.first_name||u.login_username)}">حذف الحساب</button>`:''}</div></article>`).join('')||'<p class="muted">لا توجد حسابات.</p>';$$('.toggle-user').forEach(b=>b.addEventListener('click',async()=>{const {r,data}=await apiJSON(`/api/admin/users/${b.dataset.id}`,{method:'PATCH',body:JSON.stringify({is_active:Number(b.dataset.active)===1})});status($("#globalStatus"),r.ok?'تم تحديث الحساب.':err(data.error),r.ok?'success':'error');await loadUsers();await adminStats()}));$$('.delete-user').forEach(b=>b.addEventListener('click',()=>openDeleteUserModal(b.dataset.id,b.dataset.name)))}
let pendingDeleteUserId=null;
function openDeleteUserModal(id,name){pendingDeleteUserId=Number(id);$("#deleteUserName").textContent=name||"هذا الحساب";hide($("#deleteUserStatus"));openModal($("#deleteUserModal"))}
async function confirmDeleteUser(){if(!pendingDeleteUserId)return;const btn=$("#deleteUserConfirmBtn");btn.disabled=true;btn.textContent="جاري الحذف…";try{const {r,data}=await apiJSON(`/api/admin/users/${pendingDeleteUserId}/delete`,{method:'POST',body:'{}'});if(!r.ok){status($("#deleteUserStatus"),err(data.error),'error');return}closeModal($("#deleteUserModal"));pendingDeleteUserId=null;status($("#globalStatus"),'تم حذف الحساب بنجاح.','success');await loadUsers();await adminStats()}catch{status($("#deleteUserStatus"),'تعذر الاتصال بالخادم.','error')}finally{btn.disabled=false;btn.textContent="نعم، حذف الحساب"}}
async function createUser(e){e.preventDefault();const role=$("#newRole").value,payload={name:$("#newName").value.trim(),role,username:$("#newUsername").value.trim(),password:$("#newPassword").value,telegram_user_id:$("#newTelegramUser").value,telegram_chat_id:$("#newTelegramChat").value};const {r,data}=await apiJSON('/api/admin/users',{method:'POST',body:JSON.stringify(payload)});status($("#createUserStatus"),r.ok?'تم إنشاء الحساب بنجاح.':err(data.error),r.ok?'success':'error');if(r.ok){e.target.reset();await loadUsers();await adminStats()}}
async function loadMosque(){const {r,data}=await apiJSON('/api/admin/mosque');if(!r.ok||!data.mosque)return;$("#mosqueName").value=data.mosque.name||'';$("#mosqueLat").value=data.mosque.latitude??'';$("#mosqueLon").value=data.mosque.longitude??'';$("#mosqueTz").value=data.mosque.timezone||'Asia/Riyadh'}
async function saveMosque(e){e.preventDefault();const {r,data}=await apiJSON('/api/admin/mosque',{method:'POST',body:JSON.stringify({name:$("#mosqueName").value,latitude:$("#mosqueLat").value,longitude:$("#mosqueLon").value,timezone:$("#mosqueTz").value})});status($("#mosqueStatus"),r.ok?'تم حفظ بيانات الجامع.':err(data.error),r.ok?'success':'error')}
async function loadSubscribers(){const {r,data}=await apiJSON('/api/admin/subscribers');if(!r.ok)return;$("#subscribersList").innerHTML=(data.subscribers||[]).map(s=>`<article class="simple-row"><div><strong>${esc([s.first_name,s.last_name].filter(Boolean).join(' ')||s.username||'مشترك')}</strong><small>Chat ID: ${esc(s.telegram_chat_id)}</small></div><span class="state">${Number(s.is_active)===1?'نشط':'متوقف'}</span></article>`).join('')||'<p class="muted">لا يوجد مشتركون.</p>'}
async function loadAudit(){const {r,data}=await apiJSON('/api/admin/audit');if(!r.ok)return;$("#auditList").innerHTML=(data.audit||[]).map(a=>`<article class="simple-row"><div><strong>${esc(a.action)} · ${a.result==='SUCCESS'?'نجاح':'فشل'}</strong><small>${esc(a.actor||'النظام')} · ${esc(a.created_at||'')}</small></div></article>`).join('')||'<p class="muted">لا توجد سجلات.</p>'}

async function loadMessageTemplates(){const {r,data}=await apiJSON('/api/admin/messages');if(!r.ok){status($("#messageTemplatesStatus"),err(data.error),"error");return}const box=$("#messageTemplatesList");if(!box)return;box.innerHTML=(data.templates||[]).map(t=>`<article class="card message-template-card"><div class="message-template-head"><div><strong>${esc(t.label)}</strong><small>${(t.placeholders||[]).length?`المتغيرات: ${(t.placeholders||[]).map(esc).join("، ")}`:"بدون متغيرات"}</small></div><button type="button" class="btn btn-ghost btn-sm reset-template" data-key="${esc(t.key)}" data-default="${encodeURIComponent(t.default_text||"")}">الافتراضي</button></div><textarea class="message-template-input" data-template-key="${esc(t.key)}" rows="6" maxlength="3500">${esc(t.text||"")}</textarea></article>`).join("");$$('.reset-template',box).forEach(b=>b.addEventListener('click',()=>{const i=box.querySelector(`[data-template-key="${CSS.escape(b.dataset.key)}"]`);if(i)i.value=decodeURIComponent(b.dataset.default||"")}))}
async function saveMessageTemplates(){const btn=$("#saveMessageTemplatesBtn"),templates={};$$('[data-template-key]').forEach(i=>templates[i.dataset.templateKey]=i.value.trim());btn.disabled=true;try{const {r,data}=await apiJSON('/api/admin/messages',{method:'POST',body:JSON.stringify({templates})});status($("#messageTemplatesStatus"),r.ok?'تم حفظ جميع الرسائل بنجاح.':err(data.error),r.ok?'success':'error')}finally{btn.disabled=false}}
function updateBroadcastPreview(){const text=$("#broadcastMessage")?.value||"";if($("#broadcastCount"))$("#broadcastCount").textContent=String(text.length);if($("#broadcastPreview"))$("#broadcastPreview").textContent=text||"ستظهر معاينة الرسالة هنا."}
async function sendBroadcast(e){e.preventDefault();const text=$("#broadcastMessage").value.trim(),audience=$("#broadcastAudience").value;if(!text){status($("#broadcastStatus"),"اكتب نص الرسالة أولًا.","warning");return}if(!window.confirm("هل أنت متأكد من إرسال هذه الرسالة الآن؟"))return;const btn=$("#broadcastSendBtn");btn.disabled=true;btn.textContent="جاري تجهيز الإرسال…";try{const {r,data}=await apiJSON('/api/admin/broadcast',{method:'POST',body:JSON.stringify({message:text,audience})});if(!r.ok){status($("#broadcastStatus"),err(data.error),"error");return}status($("#broadcastStatus"),`تم اعتماد الرسالة وبدأ الإرسال إلى ${Number(data.recipients||0)} مستلمًا.`,"success");e.target.reset();updateBroadcastPreview()}catch{status($("#broadcastStatus"),"تعذر الاتصال بالخادم.","error")}finally{btn.disabled=false;btn.textContent="إرسال الرسالة"}}
async function changePassword(e){e.preventDefault();const {r,data}=await apiJSON('/api/auth/change-password',{method:'POST',body:JSON.stringify({current_password:$("#currentPassword").value,new_password:$("#changePassword").value})});status($("#passwordStatus"),r.ok?'تم تغيير كلمة المرور.':err(data.error),r.ok?'success':'error');if(r.ok)e.target.reset()}
async function adminResetTestMode(){const btn=$("#adminResetTestModeBtn"),box=$("#adminTestResetStatus");if(!btn)return;if(!window.confirm("سيتم إنهاء كل حالات التجربة الحالية وإرجاع حسابات مؤذن التجربة للوقت الحقيقي. هل تريد المتابعة؟"))return;btn.disabled=true;try{const {r,data}=await apiJSON('/api/admin/test-mode/reset',{method:'POST',body:'{}'});status(box,r.ok?`تمت إعادة تعيين وضع التجربة بنجاح (${Number(data.test_users||0)} حساب). الساعة الآن تتبع الوقت الحقيقي مباشرة.`:err(data.error),r.ok?'success':'error')}catch{status(box,'تعذر الاتصال بالخادم.','error')}finally{btn.disabled=false}}
async function initAdmin(){if(!$("#adminSubscribers"))return;const me=await protect('ADMIN');if(!me)return;await Promise.all([adminStats(),loadUsers(),loadMosque()]);$$('[data-admin-tab]').forEach(b=>b.addEventListener('click',async()=>{$$('[data-admin-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-admin-page]').forEach(x=>x.classList.toggle('hidden',x.dataset.adminPage!==b.dataset.adminTab));if(b.dataset.adminTab==='subscribers')await loadSubscribers();if(b.dataset.adminTab==='messages')await loadMessageTemplates();if(b.dataset.adminTab==='audit')await loadAudit()}));$("#createUserForm")?.addEventListener('submit',createUser);$("#mosqueForm")?.addEventListener('submit',saveMosque);$("#passwordForm")?.addEventListener('submit',changePassword);$("#saveMessageTemplatesBtn")?.addEventListener('click',saveMessageTemplates);$("#broadcastForm")?.addEventListener('submit',sendBroadcast);$("#broadcastMessage")?.addEventListener('input',updateBroadcastPreview);$("#adminResetTestModeBtn")?.addEventListener('click',adminResetTestMode);updateBroadcastPreview();$("#newRole")?.addEventListener('change',()=>$$('.muadhin-fields').forEach(x=>x.classList.toggle('hidden',$("#newRole").value==='ADMIN')));$$('[data-delete-user-close]').forEach(b=>b.addEventListener('click',()=>closeModal($("#deleteUserModal"))));$("#deleteUserConfirmBtn")?.addEventListener('click',confirmDeleteUser)}


async function initDelegationCreator(){if(!$(".delegation-page"))return;const me=await protect("MUADHIN");if(!me)return;await setupDelegationDates();await loadDelegations();$("#delegationForm")?.addEventListener("submit",createDelegation);$("#addDelegationDayBtn")?.addEventListener("click",addDelegationDay);$("#copyDelegationBtn")?.addEventListener("click",e=>copyDelegationLink(Number(e.currentTarget.dataset.id)||state.lastDelegationId,e.currentTarget));$$("[data-delegation-copy-close]").forEach(b=>b.addEventListener("click",closeDelegationCopyModal))}

function delegateCountdownText(seconds){
  const total=Math.max(0,Math.floor(Number(seconds)||0));
  if(total<=0)return "حان الوقت";
  const days=Math.floor(total/86400),hours=Math.floor((total%86400)/3600),mins=Math.floor((total%3600)/60),secs=total%60;
  if(days>0)return `${days} يوم ${hours} س ${mins} د`;
  if(hours>0)return `${hours} س ${mins} د ${String(secs).padStart(2,"0")} ث`;
  return `${mins} د ${String(secs).padStart(2,"0")} ث`;
}
async function initDelegate(){
  if(!$("#delegateConfirm"))return;
  const token=new URLSearchParams(location.search).get("token")||"",info=$("#delegateInfo"),loginBox=$("#delegateLogin"),sessionBox=$("#delegateSession"),actions=$("#delegateActions"),completeBox=$("#delegateComplete");
  if(!token){status($("#delegateStatus"),"رابط التفويض غير صالح.","error");return}
  let meta=null,pin="",timer=null,anchor=0,refreshing=false;
  function stopTimer(){if(timer){clearInterval(timer);timer=null}}
  function renderCountdowns(){
    if(!meta||meta.delegation_complete)return;
    const elapsed=Math.floor((Date.now()-anchor)/1000),a=Number(meta.seconds_to_adhan),i=Number(meta.seconds_to_iqama);
    const ar=$("#delegateAdhanCountdown"),ir=$("#delegateIqamaCountdown");
    if(ar)ar.textContent=Number.isFinite(a)?delegateCountdownText(a-elapsed):"—";
    if(ir)ir.textContent=Number.isFinite(i)?delegateCountdownText(i-elapsed):"—";
    const adhanDue=!meta.current_adhan_confirmed&&!meta.action_adhan_available&&Number.isFinite(a)&&a-elapsed<=0&&Number.isFinite(i)&&i-elapsed>0,iqamaDue=!meta.current_iqama_confirmed&&!meta.action_iqama_available&&Number.isFinite(i)&&i-elapsed<=0,expired=!meta.current_iqama_confirmed&&meta.action_iqama_available&&Number.isFinite(i)&&i-elapsed<=-600;if((adhanDue||iqamaDue||expired)&&!refreshing){refreshing=true;refreshDelegation().finally(()=>refreshing=false)}
  }
  function startTimer(){stopTimer();anchor=Date.now();renderCountdowns();timer=setInterval(renderCountdowns,1000)}
  function renderDelegateSchedule(data){const box=$("#delegateSchedule");if(!box)return;const rows=data.schedule||[];box.innerHTML=rows.map(row=>`<div class="delegate-mini-day ${row.is_today?"today":""}"><span>${row.is_today?"اليوم":esc(hijriText(row.date))}</span><strong>${(row.prayers||[]).map(x=>esc(x.name_ar)).join("، ")||"—"}</strong></div>`).join("")||'<p class="muted">لا توجد صلوات قادمة ضمن هذا التفويض.</p>'}
  function renderDelegateSession(data){
    meta=data;
    document.body.classList.add("delegate-authenticated");loginBox.classList.add("hidden");info.classList.add("hidden");renderDelegateSchedule(data);
    if(data.delegation_complete){stopTimer();sessionBox.classList.add("hidden");actions.classList.add("hidden");completeBox?.classList.remove("hidden");hide($("#delegateStatus"));return}
    completeBox?.classList.add("hidden");sessionBox.classList.remove("hidden");actions.classList.remove("hidden");
    $("#delegatePrayerName").textContent=data.action_prayer_ar||"—";
    $("#delegateDateText").textContent=data.action_prayer_date?hijriText(data.action_prayer_date):"—";
    $("#delegateAdhanTime").textContent=data.action_adhan_time?`الأذان ${time12(data.action_adhan_time)}`:"—";
    $("#delegateIqamaTime").textContent=data.action_iqama_time?`الإقامة ${time12(data.action_iqama_time)}`:"—";
    $("#delegateAdhanState").textContent=data.current_adhan_confirmed?"تم إرسال إشعار الأذان":"لم يتم إرسال إشعار الأذان";
    $("#delegateIqamaState").textContent=data.current_iqama_confirmed?"تم إرسال إشعار الإقامة":"لم يتم إرسال إشعار الإقامة";
    $$(".delegate-action").forEach(b=>{const isAdhan=b.dataset.event==="ADHAN",done=isAdhan?data.current_adhan_confirmed:data.current_iqama_confirmed,available=isAdhan?data.action_adhan_available:data.action_iqama_available;b.disabled=!data.current_allowed||!!done||!available;b.dataset.warned="0";b.classList.toggle("is-complete",!!done);if(isAdhan)b.innerHTML=done?"<span>✓</span> تم إرسال إشعار الأذان":available?"<span>🔔</span> تأكيد رفع الأذان":data.action_iqama_available?"<span>🔒</span> انتهى وقت تأكيد الأذان":"<span>⏳</span> لم يحن وقت الأذان بعد";else b.innerHTML=done?"<span>✓</span> تم إرسال إشعار الإقامة":available?"<span>🕌</span> تأكيد إقامة الصلاة":"<span>⏳</span> لم يحن وقت الإقامة بعد"});
    hide($("#delegateStatus"));startTimer();
  }
  async function access(){return apiJSON('/api/delegate/access',{method:'POST',body:JSON.stringify({token,pin})})}
  async function refreshDelegation(){
    if(!pin)return;const {r,data}=await access();if(!r.ok){status($("#delegateStatus"),err(data.error),'error');return}renderDelegateSession(data)
  }
  async function enterDelegation(){
    pin=$("#delegatePin").value;
    if(!/^\d{4,8}$/.test(pin)){status($("#delegateStatus"),"أدخل الرمز السري للتفويض.","warning");return}
    const btn=$("#delegateLoginBtn");btn.disabled=true;
    try{const {r,data}=await access();if(!r.ok){status($("#delegateStatus"),err(data.error),'error');return}renderDelegateSession(data);if(!data.valid&&data.action_waiting)status($("#delegateStatus"),"التفويض قادم، ويمكنك متابعة العد التنازلي من الآن.","info");if(data.state_degraded)status($("#delegateStatus"),"تم تسجيل الدخول، لكن تعذر تحديث عدادات المواقيت الآن. ستتحدث تلقائيًا عند توفر الخدمة.","info")}
    finally{btn.disabled=false}
  }
  $("#delegateLoginBtn")?.addEventListener('click',enterDelegation);
  $("#delegatePin")?.addEventListener('keydown',e=>{if(e.key==='Enter')enterDelegation()});
  $$('.delegate-action').forEach(b=>b.addEventListener('click',async()=>{
    if(!meta||meta.delegation_complete)return;
    const isIqama=b.dataset.event==="IQAMA",needsAck=isIqama&&!meta.current_adhan_confirmed;
    if(needsAck&&b.dataset.warned!=="1"){b.dataset.warned="1";b.textContent="نعم، متابعة إرسال إشعار الإقامة";status($("#delegateStatus"),"تنبيه: لم يتم إرسال إشعار أذان هذه الصلاة. إذا كنت على علم بذلك اضغط الزر مرة أخرى للمتابعة.","warning");return}
    b.disabled=true;let completed=false;
    try{const {r,data}=await apiJSON('/api/delegate/confirm',{method:'POST',body:JSON.stringify({token,pin,event_type:b.dataset.event,ack_missing_adhan:needsAck})});if(!r.ok){status($("#delegateStatus"),err(data.error),'error');return}completed=true;const [msg,type]=deliveryMessage(data);status($("#delegateStatus"),msg,type);await refreshDelegation()}
    finally{if(!completed&&!meta?.delegation_complete){const isAdhan=b.dataset.event==="ADHAN",done=isAdhan?meta?.current_adhan_confirmed:meta?.current_iqama_confirmed,available=isAdhan?meta?.action_adhan_available:meta?.action_iqama_available;b.disabled=!!done||!available}}
  }));
}

// تشغيل الصفحات من ملف خارجي فقط حتى تبقى CSP صارمة ولا نحتاج unsafe-inline.
document.addEventListener('DOMContentLoaded',async()=>{$("#logoutBtn")?.addEventListener('click',logout);await initLogin();await initMuadhin();await initAdhanSettingsPage();await initIqamaSettingsPage();await initAdmin();await initDelegationCreator();await initDelegate()});
