const API_BASE="https://mosque-api.5jfwpmvt9w.workers.dev";
const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();
const qs=new URLSearchParams(location.search),eventId=Number(qs.get("event_id"));
const $=s=>document.querySelector(s);let meta=null;
function show(msg,type="info"){const e=$("#miniStatus");e.textContent=msg;e.className=`status-box ${type}`}
function finishLoading(){const t=$("#miniText");if(t&&t.textContent.includes("جاري التحقق")){t.textContent="";t.classList.add("hidden")}}
async function post(path,payload){const r=await fetch(`${API_BASE}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});return{r,data:await r.json().catch(()=>({}))}}
async function init(){if(!tg?.initData||!eventId){finishLoading();show("لا يمكن التحقق من جلسة Telegram.","error");return}const {r,data}=await post("/api/telegram/miniapp/context",{init_data:tg.initData,event_id:eventId});if(!r.ok){finishLoading();show("هذا الطلب غير متاح أو انتهى وقته.","error");return}meta=data;finishLoading();$("#miniText").classList.remove("hidden");$("#miniTitle").textContent=data.event_type==="ADHAN"?"تأكيد إرسال إشعار الأذان":"تأكيد إرسال إشعار الإقامة";$("#miniText").textContent=`هل أنت متأكد أنك تريد إرسال إشعار ${data.event_type==="ADHAN"?"أذان":"إقامة"} صلاة ${data.prayer_ar}؟`;$("#miniWarning").classList.toggle("hidden",!data.missing_adhan);$("#miniConfirm").disabled=!!data.already_confirmed;if(data.already_confirmed)show("تم تأكيد هذا الحدث مسبقًا.","info")}
$("#miniCancel").addEventListener("click",()=>tg?.close());$("#miniConfirm").addEventListener("click",async()=>{const b=$("#miniConfirm");b.disabled=true;const {r,data}=await post("/api/telegram/miniapp/confirm",{init_data:tg.initData,event_id:eventId,ack_missing_adhan:!!meta?.missing_adhan});if(!r.ok){show(data.error==="ADHAN_NOT_CONFIRMED_WARNING"?"يجب الإقرار بأن الأذان لم يُؤكد.":"تعذر تنفيذ التأكيد أو انتهى وقته.","error");b.disabled=false;return}show(data.test_mode?"تم تسجيل التأكيد في وضع التجربة ✅":"تم تسجيل التأكيد وإرسال الإشعار للمشتركين ✅","success");setTimeout(()=>tg?.close(),700)});init();
